# Generated by Django 5.1.3 on 2024-11-14 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_address', models.CharField(blank=True, max_length=255, null=True)),
                ('store_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('check_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_type', models.CharField(blank=True, max_length=20, null=True)),
                ('card_last_four_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('payment_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.receipt')),
            ],
        ),
    ]
