# Generated by Django 5.1.3 on 2024-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
