# Generated by Django 5.1.3 on 2024-11-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_receipt_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='card_type',
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
